"""nullable

Revision ID: 3eb59037b17b
Revises: c5fe6b385d6a
Create Date: 2022-09-08 21:56:41.141568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eb59037b17b'
down_revision = 'c5fe6b385d6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authors', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('authors', 'author',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.add_column('books', sa.Column('author_id', sa.ARRAY(sa.Integer()), nullable=True))
    op.drop_column('books', 'author')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('books', 'author_id')
    op.alter_column('authors', 'author',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('authors', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
