"""create account table again

Revision ID: 65b844fc1cf9
Revises: 869f27a353ad
Create Date: 2022-09-08 14:44:21.965181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65b844fc1cf9'
down_revision = '869f27a353ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('genre', sa.Enum('FICTION_SciFi', 'FICTION_YA', 'FICTION_Historical', 'NONFICTION_Coding', 'NONFICTION_Support', 'NONFICTION_Security', 'NONFICTION_Religion', 'LANGUAGE_French', 'LANGUAGE_German', 'LANGUAGE_Spanish', 'LANGUAGE_Portuguese', 'LANGUAGE_Italian', 'LANGUAGE_Classics', name='genre'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('isbn_10', sa.String(length=20), nullable=True),
    sa.Column('isbn_13', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_published', sa.Date(), nullable=True),
    sa.Column('amzn_link', sa.String(length=100), nullable=True),
    sa.Column('img_link', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
