"""nullable2

Revision ID: 6888254749f6
Revises: 3eb59037b17b
Create Date: 2022-09-08 22:06:20.364410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6888254749f6'
down_revision = '3eb59037b17b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_authors_name', table_name='authors')
    op.create_index(op.f('ix_authors_name'), 'authors', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_authors_name'), table_name='authors')
    op.create_index('ix_authors_name', 'authors', ['name'], unique=False)
    # ### end Alembic commands ###
