"""added optionals

Revision ID: 83b3acba4d16
Revises: cb9361695f10
Create Date: 2022-09-08 22:22:02.167796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83b3acba4d16'
down_revision = 'cb9361695f10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
